[package]
name = "CP-Review"
version = "0.1.0"
authors = ["granddaifuku"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rocket = "0.4.5"
validator = { version = "0.12", features = ["derive"] }
sqlx = { version = "0.4.1", features = ["postgres"] }

[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["uuid"]
